const Project = [
    {
        id: "1",
        title: "Aark Digital",
        slug: "Aark Digital",
        image: '/images/Projects/aark.png',
        technology: "React.js, Node.js, ethers.js, Solidity, Hardhat, TypeScript, TailwindCSS, PostgreSQL, Docker",
        preview_url: "https://aark.digital/",
        short_description: `Aark Digital is a decentralized exchange (DEX) for professional traders that offers Leveraged LP and leverage trading of Super Long Tail Assets.`,
    },
    {
        id: "2",
        title: "AegisWeb3",
        slug: "AegisWeb3",
        image: '/images/Projects/agis_web3.png',
        technology: "React.js, Node.js, ethers.js, Solidity, Hardhat, TypeScript, TailwindCSS, PostgreSQL",
        preview_url: "https://www.aegisweb3.com/",
        short_description: `AegisWeb3 is a blockchain security tool developed by the blockchain security company PeckShield, acting as a free browser extension to protect Web3 users from phishing scams, malicious tokens, and harmful transactions.`,
    },
    {
        id: "3",
        title: "Colonize",
        slug: "Colonize",
        image: '/images/Projects/game_1.png',
        technology: "React.js, Node.js, ethers.js, Solidity, Foundry, TypeScript, TailwindCSS, PostgreSQL, Docker",
        preview_url: "https://www.fusionist.io/",
        short_description: `A building simulation game focused on resource management and industrial production. Players excavate minerals, build facilities, and manufacture Mechs, creating interstellar trade networks.`,
    },
    {
        id: "4",
        title: "Mahjong Meta",
        slug: "Mahjong Meta",
        image: '/images/Projects/game_2.png',
        technology: "React.js, Node.js, ethers.js, Solidity, Hardhat, TypeScript, TailwindCSS, PostgreSQL, Docker",
        preview_url: "https://www.mjmeta.io/en/index",
        short_description: `The NFT system is the core asset system in Mahjong Meta, providing players with various functional, profitable, decorative, and aesthetic features.`,
    },
    {
        id: "5",
        title: "Rebase.gg",
        slug: "Rebase.gg",
        image: '/images/Projects/game_3.png',
        technology: "React.js, React Native, Node.js, ethers.js, Rust, Anchor, TypeScript, TailwindCSS, PostgreSQL, Docker",
        preview_url: "https://rebase.gg/home",
        short_description: `Rebase.gg is a blockchain platform and lifestyle application that blends real-world exploration with augmented reality (AR) and web3 features, allowing users to find and collect digital rewards in real life.`,
    },
    {
        id: "6",
        title: "Spin",
        slug: "Spin",
        image: '/images/Projects/spin.png',
        technology: "React.js, React Native, Node.js, ethers.js, Rust, Anchor, TypeScript, TailwindCSS, PostgreSQL, Docker",
        preview_url: "https://www.spin.fi/",
        short_description: `Spin (spin.fi) is a decentralized, multichain infrastructure platform for on-chain derivatives trading, offering a decentralized exchange (DEX) that provides a centralized exchange (CEX)-competitive user experience for trading order books on networks like NEAR and Solana. The platform uses innovative mechanisms, such as Decentralized Option Vaults (DOVs) and a Risk Engine, to facilitate complex financial products and expand the capabilities of the decentralized finance (DeFi) ecosystem.`,
    },
    {
        id: "7",
        title: "Chainflip",
        slug: "Chainflip",
        image: '/images/Projects/chainfelip.png',
        technology: "React.js, React Native, Node.js, ethers.js, Rust, Anchor, TypeScript, TailwindCSS, PostgreSQL, Docker",
        preview_url: "https://chainflip.io/",
        short_description: `Chainflip is a decentralised protocol that enables native, cross-chain swaps without the need for wrapped tokens or intermediaries. Simply select your pair, send your funds, and Chainflip completes the swap natively and securely.`,
    },
    {
        id: "8",
        title: "Ledger Crypto Wallet",
        slug: "Ledger Crypto Wallet",
        image: '/images/Projects/ledger.png',
        technology: "React, Node.js, TypeScript",
        preview_url: "https://www.ledger.com/",
        short_description: `The core of Ledger.com in blockchain is its function as a secure digital asset management platform, providing hardware wallets and the Ledger Live application to protect and manage cryptocurrencies and digital assets.`,
    },
    {
        id: "9",
        title: "Messari Crypto Research",
        slug: "Messari Crypto Research",
        image: '/images/Projects/messari.png',
        technology: "React.js, React Native, Node.js, ethers.js, Rust, Anchor, TypeScript, TailwindCSS, PostgreSQL, Docker",
        preview_url: "https://messari.io/",
        short_description: `Messari serves as a central hub for research and data related to the cryptoeconomy. With customizable and user-friendly features, it offers: Comprehensive project, exchange, & fundraising information: Access detailed data on thousands of crypto assets and projects, as well as hundreds of exchanges.`,
    },
    {
        id: "10",
        title: "Hantom",
        slug: "Hantom",
        image: '/images/Projects/hantom.png',
        technology: "React.js, React Native, Node.js, ethers.js, Rust, Anchor, TypeScript, TailwindCSS, PostgreSQL, Docker",
        preview_url: "https://devnet.hatom.com/",
        short_description: `The core point of Hatom (hatom.com) is to provide a comprehensive and decentralized finance (DeFi) ecosystem on the MultiversX blockchain, offering a non-custodial liquidity protocol with lending, borrowing, and liquid staking services to enhance DeFi growth, security, and user accessibility. `,
    },
    {
        id: "11",
        title: "Leo Wallet",
        slug: "Leo Wallet",
        image: '/images/Projects/leo.png',
        technology: "React.js, React Native, Node.js, ethers.js, Rust, Anchor, TypeScript, TailwindCSS, PostgreSQL, Docker",
        preview_url: "https://www.leo.app/",
        short_description: `The core of the Leo Wallet is its integration with the Aleo blockchain and its use of zero-knowledge proofs (ZKPs) to enable private, secure, and anonymous transactions.`,
    },
    {
        id: "12",
        title: "SweatCoin",
        slug: "SweatCoin",
        image: '/images/Projects/sweatcoin.png',
        technology: "React.js, React Native, Node.js, ethers.js, Rust, Anchor, TypeScript, TailwindCSS, PostgreSQL, Docker",
        preview_url: "https://sweatco.in/",
        short_description: `he core of sweatco.in is its blockchain integration on the NEAR Protocol to reward users for physical activity with SWEAT tokens. The Sweat Economy platform uses the Sweatcoin app to track steps and convert them into SWEAT cryptocurrency, which is then stored in the Sweat Wallet.`,
    },
];

export default Project;